name: Update README

on:
  schedule: [{cron: "0 6 */1 * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  markscribe:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      
    steps:
      - uses: actions/checkout@v4

      - uses: muesli/readme-scribe@master
        env:
          GITHUB_TOKEN: ${{ secrets.README_TOKEN }}
        with:
          template: "templates/README.md.tpl"
          writeTo: "README.md"

      - uses: actions/upload-artifact@v5
        with:
          name: README.md
          path: README.md

      - uses: stefanzweifel/git-auto-commit-action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.README_TOKEN }}
        with:
          commit_message: Update generated README
          branch: main
          commit_user_name: readme-scribe 🤖
          commit_user_email: actions@github.com
          commit_author: readme-scribe 🤖 <actions@github.com>